// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jszwwkwfrngzzawekoif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impzend3a3dmcm5nenphd2Vrb2lmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1OTYyNjMsImV4cCI6MjA3MTE3MjI2M30.p16-n_4LYRJnWo9YmNgn_BAb-CSci0l2veEVROz7N_Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});